### ISSUE TITLE
Enhancement Request: Implement Time-based Data Indexing for Improved Node Monitoring for Validators

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#17]
### Reward Size in USD

500 USD

### Reward category

Documentation

### Description

Today, there are no tools available to assist validators in visualizing and analyzing the statistics of their nodes over time. The purpose of this DevReward is to develop a comprehensive dataset that enables validators to access various time series data, such as the daily cumulative staked amount, by utilizing raw data including the number of stakers, total CSPR staked, rewards, delegation, and undelegation.

Granularity: The data should be captured at the end of each block or era, providing a detailed and accurate representation of the node's performance.

### Acceptance Criteria

- Modify the Casper Blockchain Statistic Webpage parser and utilize the JSON-RPC endpoint to index all validators' data.
- Create a materialized view in the database to filter and structure the data, enabling the creation of a "readable" stream.
- Implement GraphQL requests that can be called by frontend components, providing efficient and flexible data retrieval.
- Ensure that the development process prioritizes performance, minimizing the time taken for queries and API calls.
- Make it a requirement that the code developed for this project is open source, promoting transparency and collaboration in the developer community.

**Comment by KillianH** [comment]
Can you point to the correct repo that needs to be updated ?

**Comment by NicolasZoellner** [comment]
Good morning Killian,
Let me check this with the technical expert.
Unfortunately he is off today.
Will follow up early next week.

Best
Nicolas

**Comment by NicolasZoellner** [comment]
@KillianH,

There isn't a specific repository available for this. However, if you decide to make it open source, you can implement it on https://div3.in/.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
The result was delivered and implemented and can be seen at: https://scansper.com/
Thank you very much for your work!
