### ISSUE TITLE
Feature Request: Add Node Statistics Section to Validator Pages for Detailed Casper Blockchain Data Display

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#18]
### Reward Size in USD

500 USD

### Reward category

Documentation

### Description

Today, there is a lack of tools available to assist validators in visualizing and analyzing the statistics of their nodes over time. The objective of this DevReward is to create new graphs on websites that display relevant Casper Blockchain data. These graphs will provide a convenient way for node owners and the community to track validator statistics over time. The data displayed will include information such as the number of stakers, total CSPR staked, rewards, delegation, and undelegation. By providing this visual representation of the data, validators and the community will be able to easily monitor and analyze the performance and trends of the validators.

### Acceptance Criteria

In addition to the existing features of the Casper-Blockchain statistics website, a new section will be introduced on the individual pages of all validators. This section will include graphs that provide valuable insights into various aspects of the validator's performance over time. The following graphs will be included:

- Rewards Earned Over Time: This graph will visualize the rewards earned by the validator over a specific period. It will allow validators and the community to track the growth of rewards and identify any patterns or trends.

- Total CSPR Staked Over Time: This graph will display the total amount of CSPR staked with the validator over time. It will provide an overview of the validator's staking activity and showcase the growth of the stake.

- Delegate Action Over Time: This graph will illustrate the delegation activity associated with the validator over a given timeframe. It will demonstrate the inflow of delegation and highlight periods of increased or decreased delegation.

- Undelegate Action Over Time: This graph will showcase the undelegation activity related to the validator. It will help validators and the community understand the periods when undelegations occur and the impact on the validator's stake.

- Delegators Over Time: This graph will present the number of delegators associated with the validator over time. It will indicate the growth or decline in the validator's delegator base and provide insights into its popularity within the community.

- As a mandatory requirement, the code developed for the Casper-Blockchain statistics website and these additional features will be open source.

**Comment by NicolasZoellner** [comment]
Key requirements: Sourcecode has to be opensource and can be accessible.
Generate it for Website in generall.

**Comment by KillianH** [comment]
We could add that on https://div3.in and open source the whole explorer

**Comment by NicolasZoellner** [comment]
Hello Killian,

Yes, that would be great. I appreciate your input here. As you know, to
streamline the process, please put your idea together and implement it. If
you think it is ready, please feel free to send an email with the
description that shows that the acceptance criteria are met, if possible,
with a screenshot, to ***@***.***

We will review it, and if everything looks good, we will proceed with the
rewards.

Please be aware that from June 29th until August 31st, no technical
evaluation meetings will take place due to vacation.

If you have any further questions, please do not hesitate to contact me.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
@KillianH,

That's completely possible. If you're interested in pursuing this option, please feel free to proceed.

This will also work with https://div3.in/.

If you choose to proceed in this manner, it would be worthwhile to explore this DevReward:
https://github.com/casper-ecosystem/developer-rewards/issues/17

This can be integrated into your website once it becomes open source.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
The result was implemented and can be seen at: https://scansper.com/

**Comment by NicolasZoellner** [comment]
The result was implemented and can be seen at: https://scansper.com/
