### ISSUE TITLE
Developing a Graphical User Interface (GUI) for Casper-Client: Website or Standalone Application

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#24]
### Reward Size in USD

1000 USD

### Reward category

DApps

### Description

It seems that a CL dev built something similar already and published the GitHub Repo:
https://github.com/gRoussac/casper-deployer-hackathon-oct-2022
It is also available online:
https://casper.onrender.com/

Maybe this can be extended or used as a reference/starting point on how to interact with the Casper network via a website.

— Additional Features? —
Create a website which offers a UI to create deploys, test smart contracts and interact with the Casper blockchain.

Using casper-client can be very complicated since it is a command line utility which is very powerful and flexible but that is also it’s weak point:
A lot of things can go wrong and it is easy to make mistakes causing frustration when developing or testing.

Create a UI version of casper-client similar to the one already mentioned at the beginning, as a website, which can also send the deploys to the network directly

It is much more complex but offers an even better user experience if it can store user data, sessions, custom templates, doesn’t share potentially sensitive data etc.

### Acceptance Criteria

A few possible features:
Make the network selectable (MainNet, TestNet, custom)
Payment amount/Gas fees
Create collections of session-args incl. data types
Creating, editing, exporting offline deploys
RPC node (default to CA maintained ones, localhost?) incl. connection test
Templates for CEP-78.
Custom templates for own contracts which can be saved, edited, loaded

Advanced features:
Query existing contracts and provide a UI to interact with it

When delivering the solution describe the main functions in Code and what was done with all relevant information to [devrewards@casper.network](mailto:devrewards@casper.network)

**Comment by KMCreatesWorlds** [comment]
1. We will split up the proposal into Contract-Centric, so as the first one will be CEP-78 Standard.
2. A standalone website using React JS and Vite and JavaScript SDK
3. 1000 USD in CSPR
4. Dependent on the implementation, we will continue rolling out other CEP standards

**Comment by KillianH** [comment]
We've something similar to this on CasperHolders : https://testnet.casperholders.io/smartcontract

@KMCreatesWorlds / @NicolasZoellner let me know if we're missing some features :) It's already open source btw

**Comment by NicolasZoellner** [comment]
Hello Killian,

Just for the sake of having the process fully documented (and transparent),
would it be possible for you to send an email with a short description of
what you have done? Please include a few sentences that describe how the
acceptance criteria have been fulfilled, along with a screenshot or two of
the actual solution. The email address to send it to is
***@***.***

This would allow us to assess it more streamlined.

Appreciate your support
Best
Nicolas

**Comment by NicolasZoellner** [comment]
Hello @KillianH,

Thank you for your input. We have assessed it and it looks quite good. However, we do have some questions regarding the last acceptance criterion. If you'd be willing, please provide your contact information (name, email address) to devrewards@casper.network. This will enable us to arrange a brief alignment call in order to address the remaining details. 
We greatly appreciate your contribution.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
Hello @KillianH friendly reminder: Could you please send your contact information (Name, Email Address) to [devrewards@casper.network](mailto:devrewards@casper.network)? This will allow us to schedule a quick alignment call where we can address the open questions on our end. Thank you for your contribution. Best Nicolas

**Comment by anhnph** [comment]
@NicolasZoellner does issue still open or not?

**Comment by NicolasZoellner** [comment]
Hello @anhnph,

Thank you for asking. I apologize for the late reply. We are currently in the process of reevaluating all DevRewards. By the end of the week, you should receive a final answer.

Thank you for your patience.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
This DevReward is no longer considered and was closed on the 31th of January 2024
