### ISSUE TITLE
Implementing a Faucet for ERC20/CEP-18 Tokens

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-ecosystem/developer-rewards#3]
### Dev Reward Title

Implementing a Faucet for ERC20/CEP-18 Tokens

### Reward Size

200 USD

### Reward category

DeFi

### Description

Prepare a simple web UI (preferably React) with a button that people can press to get X amount of Token, redeemable only once every 24h.  A similar solution we have for the $CSPR native token on the testnet. We want an easier way of token distribution.

### Acceptance Criteria

- Check CEP-18 implementation of ERC-20 standard on Casper Network.
- Deploy CEP-18 smart contract to TestNet (with the name of your choice and supply amounting to 1 000 000 tokens)
- Create a simple web app that signs the transaction automatically
- On the website, implement a logic to distribute the tokens from the token pool:
- The user can initiate the distribution process of 1000 tokens by clicking on the button and signing the transaction, he is paying the gas fee to transfer the tokens to his account.
- There is a cooldown of 24h before he can repeat the action.
- The website checks the number of tokens left and shows this to the user.
- When delivering the solution describe the main functions in Code and what was done with all relevant information to [devrewards@casper.network](mailto:devrewards@casper.network)

**Comment by hoailinh1210** [comment]
Hi guys, @Adrian-Wrona @NicolasZoellner 
I just create an opensource project for this issue which allows to:
- Faucet CSPR
- Faucet CEP-18 token

Please review my source code here: https://github.com/hoailinh1210/casperdash-faucet
Faucet Website: https://faucet.casperdash.io/

Please correct me if I am wrong.
Thanks.

**Comment by NicolasZoellner** [comment]
Hello @hoailinh1210, 
thank you for your input. We have assessed it and have some questions about it. Could you please send your contact information (Name, Email Address) to devrewards@casper.network? This will allow us to schedule a quick alignment call where we can address the open questions on our end. Thank you for your contribution.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
Hello @hoailinh1210, friendly reminder: Could you please send your contact information (Name, Email Address) to [devrewards@casper.network](mailto:devrewards@casper.network)? This will allow us to schedule a quick alignment call where we can address the open questions on our end. Thank you for your contribution. Best Nicolas

**Comment by 0xkynz** [comment]
Hi @NicolasZoellner , 
I'm sorry for not getting back to you sooner, I just sent my information to your email.
Thanks

**Comment by NicolasZoellner** [comment]
The solution was introduced by @hoailinh1210 on 15.09.23 to the Casper Association, and all open questions were answered. All acceptance criteria were met. Therefore, the DevReward will be changed from 'Open' to 'Completed.' Thank you for your participation, @hoailinh1210!
