### ISSUE TITLE
Free Tax Tool: Develop a reward calculation tool for certain public key and for a certain timeframe (for tax documentation)

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#30]
### Reward Size in USD

500 USD

### Reward category

DApps

### Description

Currently, it is quite difficult to obtain a report for a specific period detailing all the CSPR delegation rewards of a particular address for a year, along with the corresponding price at the time when the rewards were generated. 

The solution to this issue should be a tool that is free to use and open-source. This tool will enable users to generate a list of all the rewards for a specific public key (e.g., wallet address) within a designated time period (e.g., a year). Furthermore, it should provide an option to download this information directly as a document (e.g., a .csv file), without requiring any additional user data (such as an email address). 

This tool should be accessible and user-friendly for everyone, featuring a simple GUI or should be written in cross-plattform code like Python (SDKs in Python are already available in the DevPortal Library).

   
[Proposal DevReward Tax Tool.pdf](https://github.com/casper-ecosystem/developer-rewards/files/12378325/Proposal.DevReward.Tax.Tool.pdf)

### Acceptance Criteria

1. Code must be open-source.
2. The tool should be written for example in Python levaraging Casper SDKs (No bash scripts etc.)
3. The input fields should include "Public Key Address" and "Period from/to."
4. The time period should be selectable by year (e.g., from 01. Jan 2020 00:00 to 31. Dec 2020 23:59).
5. The output should be a table with the following columns: "Era," "Date & Time," "CSPR Reward," "CSPR Price at the Time of Reward Received in $."
6. This table should be downloadable as a .csv file or in a similar format.
7. When delivering the solution describe the main functions in Code and what was done with all relevant information to devrewards@casper.network

For a clearer presentation, please refer to the attached proposal.

**Comment by gaupoit** [comment]
Very useful dApps for Casper Hodlers through.
