### ISSUE TITLE
Swift SDK update to node 1.5

### ISSUE THREAD

**Issue by tqhuy2018** [casper-ecosystem/developer-rewards#32]
### Reward Size in USD

1000 USD

### Reward category

SDK

### Description

We have developed Swift SDK for Casper node version 1.4 for the following methods https://github.com/hienbui9999/CasperSDKInSwift 

1. chain_get_state_root_hash
2. info_get_peers
3. info_get_deployment
4. info_get_status
5. chain_get_block_transfers
6. chain_get_block
7. chain_get_era_info_by_switch_block
8. status_get_item
9. state_get_dictionary_item
10. state_get_balance
11. state_get_auction_info
12. account_put_deploy

To update to node 1.5 version, it takes much time to review the whole thing, groping for testing, editing and then testing the whole thing again.

Very close estimate it took about 50-70 hours for this whole thing (12 methods).
Cost: $2900.

Because the maximum value of the proposal is $ 1000, I will split up 3 proposals each proposal 1000 $ corresponding to 4 methods.

1. chain_get_state_root_hash
2. info_get_peers
3. info_get_deployment
4. info_get_status

### Acceptance Criteria

- Following methods of the API Fully updated to 1.5 CSPR node:
   * chain_get_state_root_hash
   *  info_get_peers  
   *  info_get_deploy 
    * info_get_status 
- Unit tests

**Comment by NicolasZoellner** [comment]
Thank you, @tqhuy2018, for your proposal. We will evaluate it during the next evaluation meeting scheduled for Tuesday, September 19th.
Best regards
Nicolas

**Comment by NicolasZoellner** [comment]
Dear @tqhuy2018,

We evaluated your proposal during the technical evaluation meeting on September 19, 2023, and came to the conclusion that we would like to accept it. Please split it into three separate proposals (Part 1, 2, 3), and after a final review from our side, we will release it as three separate active DevRewards.

Thank you very much for your contribution.

Best regards,
Nicolas Zöllner

**Comment by tqhuy2018** [comment]
Dear @NicolasZoellner 

I have split it into 3 separate proposals (Part 1,2,3). Check it please.

Thank you.

Best regards
Huy Tran

**Comment by NicolasZoellner** [comment]
Hello @tqhuy2018,

Thank you for splitting them up into 3 separate topics. Please check the comment on your first proposal from Karol. I will close this one because it is now available as 3 different ones.

Best regards, 
Nicolas Zöllner
