### ISSUE TITLE
Casper Testnet: Enhancing Address Data Accessibility on Blockchain Explorer

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#46]
### Reward Size in USD

150 USD

### Reward category

DApps

### Description

Description: The Casper Testnet Blockchain is open source, but currently, not many blockchain explorers have made its data accessible. This DevReward project aims to create a data tool that provides a comprehensive overview of the blockchain's daily activity concerning addresses on explorers. The primary objective is to gain a better understanding of active wallets and wallets in general.

### Acceptance Criteria

•	The required data must be sourced from the testnet of the Casper Blockchain.

•	The newly generated daily datasets should be added to the main datasets in a timely manner and should be available as 
        .csv files within 48 hours.

•	The available categories should include the following datasets:
o	Daily active addresses (addresses that have performed at least 1 deploy)
o	Daily total of newly generated addresses
o	Daily total of all available addresses on the blockchain

•	The dataset should provide daily data points.

•	Data must be available for download in .csv format and easily accessible. It should be available for at least the year 2023 and, preferably, for the entire blockchain history up to the Genesis block if applicable.

•	The downloadable .csv datasets need to have at least the following filters to choose from:
o	Last month
o	Last year
o	All data (until Genesis or at least 2023)
o	Select time frame (with a selectable range that goes in the format "from dd.mm.yyyy to dd.mm.yyyy")

•	Consider refining the categorization and suggest more granular datasets if applicable.

•	Provide a detailed description of how the different sections were categorized, the calculations behind it, the data processing 
        methods employed, and make the source code accessible.

•	Optionally, include a graphical representation of the data over time on the explorer's webpage.

**Comment by msanlisavas** [comment]
Hello @NicolasZoellner,
I already have an explorer https://eraguardian.com. Would it be okay if I add these features to it along with #44 and #30

**Comment by msanlisavas** [comment]
I guess the dev rewards program forgotten :/

**Comment by NicolasZoellner** [comment]
Hello @msanlisavas,

My apologies for the late response. This item has already been implemented, and unfortunately, there was an issue with updating the DevReward GitHub repository. We are currently in the process of restructuring the DevReward Program.

Thank you for your interest.

Best regards,
Nicolas

**Comment by NicolasZoellner** [comment]
This DevReward was succesfully completed.
