### ISSUE TITLE
Concept Creation: Enhancing Casper Blockchain Explorer with DeFi Insights

### ISSUE THREAD

**Issue by NicolasZoellner** [casper-ecosystem/developer-rewards#47]
### Reward Size in USD

500 USD

### Reward category

DApps

### Description

The DeFi landscape is currently evolving, and TVL (Total Value Locked) is a valuable indicator of the level of activity occurring on the blockchain within the context of the DeFi ecosystem. The Casper Mainnet Blockchain is open source, and various blockchain explorers have made some of its data accessible. This DevReward project aims to create a data tool that provides a comprehensive overview of the blockchain's daily activity related to TVL and DEX (Decentralized Exchange) activity. The primary objective is to gain a better understanding of TVL on the blockchain, active DEXs, and the corresponding liquidity pools.

### Acceptance Criteria

•	The required data must be sourced from the Mainnet of the Casper Blockchain.

•	This Developer Reward is focused on Teams with  Casper Blockchain Explorer, which, in a second step, would be able to 
        include the  concept directly into their explorer if all acceptance criteria are met.

•	Prepare a robust concept and mock-up for indicating TVL, active DEXs and Bridges, and the included liquidity pools. This 
        mock-up should have the following required MVPs that can be assessed:
o	A comprehensive overview of all DEXs and bridges using the Casper Blockchain.
o	A comprehensive overview of all available liquidity pools that are included.
o	A total overview of the entire existing TVL on the Casper blockchain and the daily changes in these volumes.
o	The data should be available as downloadable .csv files.
o	Make suggestions for 5-10 KPIs that should be available and explain the added value they would bring.
o	Data must be available for download in .csv format and easily accessible. It should be available for at least the year 2023 
        and, preferably, for the entire blockchain history up to the Genesis block if applicable.

•	Provide a detailed description of how the different sections were categorized, the calculations behind them, the data 
        processing methods employed, and make the source code accessible.

•	As soon as this data and MVP are ready, schedule a meeting with the corresponding deployer of the concept and we will 
        request a demo of the MVP.

•	If all acceptance criteria are met, please provide a time schedule for implementing the solution and an implementation 
        schedule.

•	Based on these points, the concept will then be transferred to a DevReward that will cover the implementation of this 
        concept or further development until the solution is live on the corresponding Explorer.

**Comment by lukies568** [comment]
this my shit quit fucking with my shit
