### ISSUE TITLE
Smart Contract Reader

### ISSUE THREAD

**Issue by Melsn** [casper-ecosystem/developer-rewards#48]
### Reward Size in USD

600 USD

### Reward category

Other

### Description

GM readers and devs! 
I am in Crypto since 2017 and missing one feature for interacting with a smart contract. The masses dont know how to read a code. 
For the transparency sake, I always wished that there will be a meassage when you interact with the smart contract, what this smart contract is able to do if you accept. This makes it a lot harder for scammers beacause before you interact with the contract it says you, that it can drain your wallet or whatever. On the other hand it can say that the contract can only read your wallet and signing this contract is safe. 
For enterprise adoption it would be a hughe win if they dont have to care about those issues to get scammed by what ever.

I heard about the fire extension, which pops up when you sign a contract which tells you what the contract is able to do if you sign.

My public adress is 0197565a21eda48501efcc16bc20b5013ef6ce80f3b027e4f95ddef57474a6c557
You can also reach out to me via email: jhnroome@gmail.com

### Acceptance Criteria

1. Check contract as you want to sign a interaction on the Casper Network.
2. Tell the user what signing this contract does.
3. If it does what you are signing for, good! If this contract would drain your wallet, good that we know and wont sign the contract.
4. Create a feedback button for dangerous fake contracts to report them
5. If you dont have someone to do this, give me this job :p
6. I think about a message for approvals, swaps, deploys, withdrwas, sell and buy orders on the nft market whatever. Every contract you can sign 
7. Love Casper go

**Comment by Melsn** [comment]
![Fire extension example](https://github.com/casper-ecosystem/developer-rewards/assets/129516518/17f64521-6604-454e-adc4-c1b05bde7119)

**Comment by NicolasZoellner** [comment]
Hello @Melsn, thank you for the proposal. We will assess it during the next technical evaluation meeting on the 17th of October and follow up soon. 
Best regards, Nicolas.

**Comment by gaupoit** [comment]
I think we can apply this feature to our CasperDash wallet.

**Comment by NicolasZoellner** [comment]
Hello @Melsn,

We have assessed your proposal and found it to be too general and unrealistic in its description. Therefore, we have come to the conclusion that we have to decline it.

Best regards,
Nicolas

**Comment by Melsn** [comment]
Yeah I am not a dev just trying to contribute to the ecosystem :)

Thanks anyway for taking your time!
