### ISSUE TITLE
Create Vietnamese DevReward Tutorial

### ISSUE THREAD

**Issue by gaupoit** [casper-ecosystem/developer-rewards#49]
### Reward Size in USD

300 USD

### Reward category

Documentation

### Description

Vietnam is one of the biggest blockchain hubs in South East Asia, in terms of community and builders. That's the reason why we created this proposal to create the documentation and video guide about the DevReward program that can attract more Vietnamese Builders.

### Acceptance Criteria

1. Translate the README.md to Vietnamese 
2. Record the tutorial video in Vietnamese. Ref: https://www.youtube.com/watch?v=igEnUzy1OII
3. Blog post about how our builder get the reward when joining the DevReward program to solve this proposal https://github.com/casper-ecosystem/developer-rewards/issues/3
4. Create the Vietnamese Casper Builder Telegram Group to educate and support builder

**Comment by NicolasZoellner** [comment]
Hello @gaupoit, thank you very much for the proposal. We will assess it during our technical evaluation meeting, which will take place today.

Best regards,
Nicolas

**Comment by gaupoit** [comment]
> Hello @gaupoit, thank you very much for the proposal. We will assess it during our technical evaluation meeting, which will take place today.
> 
> Best regards, Nicolas

Thanks for your reply. Cannot wait to contribute our effort for the development of Casper Ecosystem.

**Comment by NicolasZoellner** [comment]
Hello @gaupoit, I apologize for the delay. We have assessed your idea and give you the green light to turn them into a DevReward. Thank you very much for your contribution!

**Comment by gaupoit** [comment]
> Hello @gaupoit, I apologize for the delay. We have assessed your idea and give you the green light to turn them into a DevReward. Thank you very much for your contribution!

Many thanks.

**Comment by fxmasterfinn** [comment]
> Hello @gaupoit, I apologize for the delay. We have assessed your idea and give you the green light to turn it into a DevReward. Thank you very much for your contribution!

Hi @NicolasZoellner,

These are our outcomes for the required criteria:

1. Translate the README.md to Vietnamese: [Link](https://docs.google.com/document/d/1bCYMnSCDf0ntMz7wwas1TdmNVKRe7pJjsAV8CLBMEi8/edit?usp=sharing)
2. Record the tutorial video in Vietnamese: [Link](https://youtu.be/iIeNk3r6Z7g?si=Wk4My0fmlIorOz_U)
3. Blog post about how our builder gets the reward when joining the DevReward program to solve this proposal: [Link](https://dev.to/casperbuilder/join-casper-devreward-program-contributing-to-receive-rewards-mfp)
4. Create the Vietnamese Casper Builder Telegram Group to educate and support builder: [Link](https://t.me/VietnameseCasperBuilders)

Looking forward to your feedback,

**Comment by NicolasZoellner** [comment]
Hello Devs, thank you very much for your contribution, we will take a look at it and will follow up to you as soon as possible.
Best regards
Nicolas

**Comment by NicolasZoellner** [comment]
@fxmasterfinn,
the Director of Developer Advocacy will contact you soon and check it with you and give feedback about it.
Best regards
Nicolas

**Comment by melpadden** [comment]
Hi. This looks good. Thank you.

**Comment by fxmasterfinn** [comment]
Many thanks @melpadden. I hope you can let us know what is the next step.

**Comment by fxmasterfinn** [comment]
Hi @NicolasZoellner since the issue was marked closed, I hope you can let me know if there's anything we should do in addition.

**Comment by NicolasZoellner** [comment]
Hey @fxmasterfinn  please send the following information to devrewards@casper.network. To initiate the process, please provide us with the following information:


- Name of DevReward
- Your CSPR Wallet Address where the tokens can be sent.
- Your Full Name.

Thank you very much.
